=== kaliiiiiiiiii/rinb/rinb_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Config",
  "type": "object",
  "properties": {
    "arch": {
      "description": "Target architecture",
      "$ref": "#/$defs/Arch",
      "default": "amd64"
    },
    "edition": {
      "description": "Windows edition",
      "$ref": "#/$defs/edition",
      "default": "Professional"
    },
    "lang": {
      "description": "Target language",
      "$ref": "#/$defs/lang",
      "default": "en-us"
    },
    "sha1size": {
      "description": "{sha1}:{sizeInBytes} for pinning",
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[0-9a-f]{40}:[0-9]+$"
    },
    "url": {
      "description": "Optional URL for pinning. Requires sha1size to be defined.",
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "version": {
      "description": "Major windows version",
      "$ref": "#/$defs/MajorWinVer",
      "default": "11"
    }
  },
  "allOf": [
    {
      "if": {
        "not": {
          "properties": {
            "url": {
              "const": null
            }
          }
        }
      },
      "then": {
        "properties": {
          "sha1size": {
            "type": "string",
            "pattern": "^[0-9a-f]{40}:[0-9]+$"
          }
        },
        "required": [
          "sha1size"
        ]
      }
    }
  ],
  "$defs": {
    "Arch": {
      "type": "string",
      "enum": [
        "amd64",
        "arm64",
        "x86"
      ]
    },
    "MajorWinVer": {
      "type": "string",
      "enum": [
        "10",
        "11"
      ]
    },
    "edition": {
      "enum": [
        "Cloud",
        "CloudN",
        "Core",
        "CoreConnected",
        "CoreConnectedCountrySpecific",
        "CoreConnectedN",
        "CoreConnectedSingleLanguage",
        "CoreCountrySpecific",
        "CoreN",
        "CoreSingleLanguage",
        "Education",
        "EducationN",
        "Enterprise",
        "EnterpriseN",
        "HomeBasic",
        "HomeBasicN",
        "HomePremium",
        "HomePremiumN",
        "Professional",
        "ProfessionalEducation",
        "ProfessionalEducationN",
        "ProfessionalN",
        "ProfessionalStudent",
        "ProfessionalStudentN",
        "ProfessionalWorkstation",
        "ProfessionalWorkstationN",
        "Starter",
        "StarterN",
        "Ultimate",
        "UltimateN"
      ]
    },
    "lang": {
      "enum": [
        "ar-sa",
        "bg-bg",
        "cs-cz",
        "da-dk",
        "de-de",
        "el-gr",
        "en-gb",
        "en-us",
        "es-es",
        "es-mx",
        "et-ee",
        "fi-fi",
        "fr-ca",
        "fr-fr",
        "he-il",
        "hr-hr",
        "hu-hu",
        "it-it",
        "ja-jp",
        "ko-kr",
        "lt-lt",
        "lv-lv",
        "nb-no",
        "nl-nl",
        "pl-pl",
        "pt-br",
        "pt-pt",
        "ro-ro",
        "ru-ru",
        "sk-sk",
        "sl-si",
        "sr-latn-rs",
        "sv-se",
        "th-th",
        "tr-tr",
        "uk-ua",
        "zh-cn",
        "zh-tw"
      ]
    }
  }
}

=== kaliiiiiiiiii/rinb/rinb.lock.json
{
  "lang": "en-us",
  "arch": "amd64",
  "edition": "Professional",
  "version": "11",
  "sha1size": "8ceab2838f8e90180ac7490e8752157fb05588cb:4680320173",
  "url": "http://dl.delivery.mp.microsoft.com/filestreamingservice/files/009d9a0d-8e1a-45ce-9540-21377534803e/26100.4349.250607-1500.ge_release_svc_refresh_CLIENTCONSUMER_RET_x64FRE_en-us.esd"
}
